name: Pylint (Static Analysis)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4  # Updated to latest v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest  # Ensure pytest is installed

    - name: Run Pylint
      continue-on-error: true  #Prevents Pylint errors from failing the workflow
      run: pylint $(git ls-files '*.py') || true

    - name: Save Pylint Report
      run: pylint $(git ls-files '*.py') > ./post_traces/pylint_report.txt || true  # ✅ Saves Pylint output

