name: Pylint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pyflakes bandit radon

      - name: Run Pylint (Static Code Analysis)
        run: |
          pylint $(git ls-files '*.py')

      - name: Run Pyflakes (Error Detection)
        run: |
          pyflakes $(git ls-files '*.py')

      - name: Run Bandit (Security Analysis)
        run: |
          bandit -r .

      - name: Run Radon (Complexity Analysis)
        run: |
          radon cc -a $(git ls-files '*.py')
